### PR TITLE
Ovolkan/sentinel tombstone

### LINKED ISSUE #479: if sentinel runs a batch of init commands, and then sentinel crashes, it will run the same batch once more; it should not; there needs to be a tombstone, maybe as a secret mounted to the fs, that sentinel checks.

### PR DESCRIPTION
**Pull request by v0lkan**
# Adds a Tombstone Secret to VSecm Sentinel

Adds the tombstone so that when VSecM Sentinel is evicted, it does not re-run the initialization commands.

Also, fixes #479.

Tested on the build server, unit and staging tests pass with flying colors.

## Changes

List the major changes you have made in bullet points:

- Added a tombstone secret.
- VSecM sentinel modifies the secret when its initialization is done.

## Test Policy Compliance

We will need to add relevant tests in a follow-up PR.

## Code Quality

- [x] I have followed the coding standards for this project.
- [x] I have performed a self-review of my code.
- [x] My code is well-commented, particularly in areas that may be difficult 
      to understand.

## Documentation

I’ll update the docs as a separate PR.

## Checklist

Before you submit this PR, please make sure:

- [x] You have read [the contributing guidelines][contributing] and 
      *especially* the [test policy][test-policy].
- [x] You have thoroughly tested your changes.
- [x] You have followed all the contributing guidelines for this project.
- [x] You understand and agree that your contributions will be publicly available 
  under the project’s license.

[contributing]: https://vsecm.com/docs/contributing/
[test-policy]: https://vsecm.com/docs/contributing/#add-tests-for-new-features

*By submitting this pull request, you confirm that my contribution is made under 
the terms of the project’s license and that you have the authority to grant 
these rights.*

---

Thank you for your contribution to [**VMware Secrets Manager**](https://vsecm.com)
🐢⚡️!

### CODE REVIEW

File: app/safe/internal/server/handle/handle.go [hunk 1]
```diff
@@ -124,6 +124,15 @@ func InitializeRoutes(source *workloadapi.X509Source) {
 			return
 		}
 
+		if r.Method == http.MethodPost && p == "/sentinel/v1/init-completed" {
```
Comment (v0lkan) [inline app/safe/internal/server/handle/handle.go:127]: VSecM Sentinel calls this endpoint and sends a bunch of commands for VSecM safe to execute in a batch.

File: helm-charts/0.22.4/charts/sentinel/templates/Deployment.yaml [hunk 2]
```diff
@@ -46,10 +46,13 @@ spec:
             - name: spire-agent-socket
               mountPath: /spire-agent-socket
               readOnly: true
-          {{- if .Values.initCommand.enabled }}
+          {{- if .Values.global.sentinelInitCommand.enabled }}
```
Comment (v0lkan) [inline helm-charts/0.22.4/charts/sentinel/templates/Deployment.yaml:49]: @abhishek44sharma — I had to put it to .Values.global (instead of values.yml of sentinel) because TCX build pipeline was not able to read it otherwise.

I also thought about creating a separate helm chart for TCX, but that would be an overkill.

If we figure out to do it cleaner in TCX, we might refactor this part again.
