### PR TITLE
Fixes unit test issues with the core package.

### LINKED ISSUE #281: Update and refactor the v1 core package based on the latest unit test results
Some of the unit tests are failing as the underlying code needs to be updated and refactored.
Improve the code coverage.
Fix the test cases for failure related to multiple key-val pairs in the provided template.

eg: https://github.com/vmware-tanzu/secrets-manager/blob/main/core/entity/data/v1/v1_test.go#L185

### PR DESCRIPTION
**Pull request by farhan-pasha**
Refactors and fixes the v1 functions to address the failing unit tests.

Fixes #281

### CODE REVIEW

File: core/entity/data/v1/v1.go [hunk 1]
```diff
@@ -162,40 +162,63 @@ func (secret SecretStored) ToMapForK8s() map[string][]byte {
...
 	// If the template fails, use the secret’s value as is.
-	err = json.Unmarshal(([]byte)(secret.Values[0]), &data)
+	return handleTemplateFailure(data, secret.Values[0])
+}
+
+// handleNoTemplate is used when there is no template defined.
+// It attempts to unmarshal the 'value' string as JSON. If successful, it returns
+// a map with the JSON key-value pairs converted to []byte values; otherwise, it
+// returns a map with a single entry, "VALUE", containing the original 'value' as []byte.
+
```
Comment (v0lkan) [inline core/entity/data/v1/v1.go:182]: nit: can we remove the extra new line between the godoc and the function definition?

Also, by convention, I’ve been declaring functions before they are used, so it would be better to move `handleNoTemplate()` and `convertMapToStringBytes()` above `func ToMapForK8s()` for consistency.

**Review by v0lkan — CHANGES_REQUESTED** [review]
I have a few nitpicks about placement of functions in the code and extra new lines between Godoc and the function header.

Other than that, it looks good. 

Thanks 🙏 .

File: core/entity/data/v1/v1_test.go [hunk 2]
```diff
@@ -475,6 +512,34 @@ func TestSecretStored_Parse(t *testing.T) {
...
+					Template: "{\"PASS\":\"{{.pass}}\"}",
+					Format:   "json",
+				},
+			},
+			want:    "{\"PASS\":\"secret\"}",
+			wantErr: false,
+			err:     nil,
+		},
+		{
+			name: "valid_values_json_passed_as_yaml",
```
Comment (abhishek44sharma) [inline core/entity/data/v1/v1_test.go:530]: Are these tests redundant here? We have these test cases as part of transform() tests.  And parse() specifically doesn't do any validation around template and format. Please correct me if I'm missing something.

File: core/entity/data/v1/v1_test.go [hunk 3]
```diff
@@ -490,16 +555,30 @@ func TestSecretStored_Parse(t *testing.T) {
...
+				Name:   "test-3",
+				Values: []string{"{\"pass\":\"secret\"}", "{\"pass_2\":\"secret-2\"}", "{\"pass_3\":\"secret-3\"}"},
 				Meta: SecretMeta{
-					Template: "PASS:{{.pass}},PASS-2:{{.pass-2}}",
+					Template: "PASS:{{.pass}},PASS_3:{{.pass_3}}",
 					Format:   "yaml",
 				},
 			},
-			want:    "[\"paass:secret\\n\",\"pass-2:secret-2\\n\"]",
+			want:    "[\"PASS:secret\",\"PASS_3:secret-3\"]",
```
Comment (abhishek44sharma) [inline core/entity/data/v1/v1_test.go:581]: +1 This is good one. Thanks!! 👍

**Review by v0lkan — APPROVED** [review]
Overall, it looks good to me.

If @farhan-pasha and @abhishek44sharma have resolved the comments in the convo, we can merge it.

File: core/entity/data/v1/v1.go [hunk 4]
```diff
@@ -162,40 +162,63 @@ func (secret SecretStored) ToMapForK8s() map[string][]byte {
...
+func handleNoTemplate(data map[string][]byte, value string) map[string][]byte {
+	var jsonData map[string]string
+	err := json.Unmarshal(([]byte)(value), &jsonData)
 	if err != nil {
-		// need to reset data if failed to unmarshal
-		data = map[string][]byte{}
```
[the remark this answers is not in the document]
Comment (v0lkan) [reply core/entity/data/v1/v1.go:191]: @farhan-pasha @abhishek44sharma — has this comment been resolved?

Also, there was a merge conflict; I fixed that on the branch, but please make sure things are still ok.

Cheers.

**Comment by farhan-pasha** [comment]
> Overall, it looks good to me.
> 
> If @farhan-pasha and @abhishek44sharma have resolved the comments in the convo, we can merge it.

Apologies for delaying this PR. Gave other issue a higher priority. Having a look now.

File: core/entity/data/v1/v1.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (farhan-pasha) [reply core/entity/data/v1/v1.go:191]: Thanks for the review @abhishek44sharma 
I double checked it, in case of failure, unmarshal() returns an error and leaves the target struct unchanged. So I think we are good here. Please let me know if I missed something here I can go back and address it.

File: core/entity/data/v1/v1_test.go (hunk 2 above)
Comment (farhan-pasha) [reply core/entity/data/v1/v1_test.go:530]: Yes, I completely agree with your comment, this test case should be part of test cases for transform().
